#
# PARAMETERS: PTMMap
#
PTMMap:

  # Folder in which filtered PTM Maps will be saved
  path_plots_with_threshold: PTMmaps_filtered
  path_plots_Without_threshold: PTMmaps

  # Plot parameters
  font_size: 50
  grid: 'No'
  plot_width: 1700
  plot_height: 850

  # Required column names
  pgm_column_name: [pgm, LEVEL]
  g_column_name: [g, REL]
  a_column_name: [a, REL]
  n_column_name: [n, REL]
  e_column_name: [e, REL]
  p_column_name: [p, LEVEL]
  q_column_name: [q, LEVEL]
  d_column_name: [d, REL]
  qf_column_name: [qf, LEVEL]
  pFreq_column_name: [pFreq, REL]
  qfFreq_column_name: [qfFreq, REL]
  pgmFreq_column_name: [pgmFreq, REL]
  first_b_column_name: [first_b, REL]
  description_column_name: [description, REL]
  Missing_Cleavages_column_name: [Missing_Cleavage, REL]

  # How Non-modified are named
  NM: NM

  # Group to be analysed
  groups:
    - GLG-CX

  # LPS integrations for: p2qc, qc2q, pgm2p, pgm2p_MN
  # [LowLevel_firstRow, LowLevel_secondRow]
  LPS_ColumnNames:
    p2qc:     [Z_p2qf_logLimma, LPS]
    qc2q:     [Z_qf2q_logLimma, LPS]
    pgm2p:    [Z_pgm2p_logLimma, LPS]
    pgm2p_NM: [Z_pgm2p_dNM_logLimma, LPS]

  # NM comparison for pgm2p integrations
  # [LowLevel_firstRow, LowLevel_secondRow]
  NM_ColumnNames:
    pgm2p:    [Z_pgm2p_dNM_limma, qvalue]
    pgm2p_NM: [Z_pgm2p_limma_NM_ONLY, qvalue]

  # Filter integrations for: p2qc, qc2q
  # [LowLevel_firstRow, LowLevel_secondRow]
  Filter_ColumnNames:
    p2qc: [Z_p2qf_limma, pvalue]
    qc2q: [Z_qf2q_limma, pvalue]

  # Threshold of filtering for the given integrations: pgm2p_NM, pgm2p, p2qf, qf2q
  threshold_pgm2p_NM: 0.05
  threshold_pgm2p: 0.05
  threshold_p2qf: 0.05
  threshold_qf2q: 0.05
  pgmFreqThreshold: 0
